export const FETCH_USERS_INFO_REQUEST = 'FETCH_USERS_INFO_REQUEST'
export const FETCH_USERS_INFO_SUCCESS = 'FETCH_USERS_INFO_SUCCESS'
export const FETCH_USERS_INFO_FAILURE = 'FETCH_USERS_INFO_FAILURE'